# Schema for the configuration files of the Panopoly Media module.

panopoly_media.settings:
  type: config_object
  label: 'Panopoly Media settings'
  mapping:
    youtube_nocookie:
      type: boolean
      label: 'Use YouTube nocookie URLs for embedded video'

action.configuration.panopoly_media_file_delete_action:
  type: action_configuration_default
  label: 'Deletes selected files'
