# Schema for the configuration files of the Panopoly Media module.

panopoly_media.settings:
  type: config_object
  label: 'Panopoly Media settings'
  mapping:
    youtube_nocookie:
      type: boolean
      label: 'Use YouTube nocookie URLs for embedded video'
